services:
  db:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27017:27017
    entrypoint: ['mongod', '--replSet', 'myReplicaSet', '--bind_ip', '0.0.0.0']
  mongosetup:
    image: mongo:6
    depends_on:
      - db
    volumes:
      - ./scripts:/scripts
    restart: 'no'
    entrypoint: ['bash', '/scripts/mongo_setup.sh']

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/data
